### ISSUE TITLE
Usage of Spray vs Proxy

### ISSUE THREAD

**Issue by jsarkisian** [blacklanternsecurity/TREVORspray#1]
Hey all, great tool!

Quick question: the spraying tool seems to allow you to round robin SSH sessions when spraying, so I'm a bit confused on the use of the proxy tool? Do these need to be used together for the tool to work correctly? In other words, set the proxy script to use the droplets I want it to, then set those same droplets in the command for the spray?

Thanks!

**Comment by TheTechromancer** [comment]
The spray tool does not need the proxy (it has the functionality built-in). The proxy is for use with other tools, e.g. BurpSuite.
