### ISSUE TITLE
Not Declared Variable.

### ISSUE THREAD

**Issue by skylerknecht** [blacklanternsecurity/TREVORspray#15]
https://github.com/blacklanternsecurity/TREVORspray/blob/3f50b24c6be2ce8fdffe3a1ec10ebd836f52466a/trevorspray/lib/sprayers/owa.py#L51

This check is unnecessary and creates an issue when the operator declares a URL as the discovery variable will not be defined.

**Comment by TheTechromancer** [comment]
Thanks for reporting. I've pushed a fix. Can you try again with the latest dev branch?

```
pip install --force-reinstall git+https://github.com/blacklanternsecurity/trevorspray@dev
```

**Comment by TheTechromancer** [comment]
Fixes have been merged into the main branch. Please let us know if you run into any other issues.
