### ISSUE TITLE
Error when supplying --url to owa spray module (on-prem owa instances)

### ISSUE THREAD

**Issue by amspartacus1** [blacklanternsecurity/TREVORspray#16]
https://github.com/blacklanternsecurity/TREVORspray/blob/3f50b24c6be2ce8fdffe3a1ec10ebd836f52466a/trevorspray/lib/sprayers/owa.py#L51-L52

When supplying an on-prem OWA url (e.g., https://mail.company.com/Autodiscover/Autodiscover.xml) via `--url` argument to `-m owa` module, the following error occurs:

```
[ERRR] Unhandled error in OWA.initialize(): local variable 'discovery' referenced before assignment
[ERRR] Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/trevorspray/lib/trevor.py", line 140, in spray
    ready = sprayer.initialize()
  File "/home/user/.local/lib/python3.9/site-packages/trevorspray/lib/sprayers/owa.py", line 52, in initialize
    discovery.owa_internal_domain(self.url)
UnboundLocalError: local variable 'discovery' referenced before assignment

[ERRR] Failed to initialize OWA
```

This is due to an unnecessary discovery check initialized at line 51 in owa.py. Commenting out or removing line 51-52 in owa.py resolves this issue.

**Comment by TheTechromancer** [comment]
Thanks for reporting. I've pushed a fix. Can you try again with the latest dev branch?

```
pip install --force-reinstall git+https://github.com/blacklanternsecurity/trevorspray@dev
```

EDIT: dup of #15

**Comment by TheTechromancer** [comment]
Fixes have been merged into the main branch. Please let us know if you run into any other issues.
