### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by cybertuxh4xor** [blacklanternsecurity/TREVORspray#17]
i am having issues installing.

I get this

└─$ sudo pip install git+https://github.com/blacklanternsecurity/trevorproxy
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.                                          
Collecting git+https://github.com/blacklanternsecurity/trevorproxy
  Cloning https://github.com/blacklanternsecurity/trevorproxy to /tmp/pip-req-build-mKi0tJ
  Running command git clone -q https://github.com/blacklanternsecurity/trevorproxy /tmp/pip-req-build-mKi0tJ
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplmnVGj                                                                      
       cwd: /tmp/pip-req-build-mKi0tJ                                                                                                                                                                                 
  Complete output (4 lines):                                                                                                                                                                                          
  Traceback (most recent call last):                                                                                                                                                                                  
    File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py", line 16, in <module>                                                                                                             
      from importlib import import_module                                                                                                                                                                             
  ImportError: No module named importlib                                                                                                                                                                              
  ----------------------------------------                                                                                                                                                                            
ERROR: Command errored out with exit status 1: /usr/bin/python /usr/local/lib/python2.7/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmplmnVGj Check the logs for full command output.

**Comment by wretiii** [comment]
Have you tried running pip3 or installing the python3-pip package?

**Comment by cybertuxh4xor** [comment]
yes, it is now installed but I cant figure out how to run it.
![image](https://user-images.githubusercontent.com/88122300/153626849-c195c2a8-23bd-42ae-822f-028c8281afcb.png)
