### ISSUE TITLE
ENHANCEMENT REQUEST: Option for Random Delay

### ISSUE THREAD

**Issue by jsarkisian** [blacklanternsecurity/TREVORspray#2]
Hello, great tool!

Was curious if there's time to add an option for delay that randomizes the amount of seconds for delay between each request up to X maximum seconds.

Thanks!

**Comment by TheTechromancer** [comment]
This has been implemented via the `--jitter` option. 68c14f9e048f48f38445f7ba23eb4501a91eccdd
