### ISSUE TITLE
Error handling command line parameters

### ISSUE THREAD

**Issue by aconite33** [blacklanternsecurity/TREVORspray#21]
When an operator makes a mistake and issues the incorrect parameters, Trevorspray errors out and doesn't prompt the user to fix their parameters.

E.g.,

```
trevorspray --users someuser --password somepassword
```

This will result in an error.

Should prompt the user to provide a domain, either in the `--user` parameter, or by providing the `-r` switch for a domain.

**Comment by TheTechromancer** [comment]
I couldn't reproduce this but I'm guessing you weren't on the latest version. (Maybe you did a `pip install trevorspray` instead of `pip install git+https://github.com/blacklanternsecurity/trevorspray`?)

Anyway I've updated the version in PyPi so it should be fixed now 👍
