### ISSUE TITLE
Feature request: allow specifying Okta domain

### ISSUE THREAD

**Issue by Anthirian** [blacklanternsecurity/TREVORspray#22]
During a red team engagement I found out that Okta makes use of multiple domains for federation. My current target makes use of the `okta-emea.com` domain, but TREVORspray has `okta.com` hardcoded in in [okta.py](https://github.com/blacklanternsecurity/TREVORspray/blob/trevorspray-v2/trevorspray/lib/sprayers/okta.py#L11):

```python
# default target URL
default_url = 'https://{subdomain}.okta.com/api/v1/authn'
```

Changing the URL allowed me to successfully spray a user account that I already knew the password for:

```python
# default target URL
default_url = 'https://{subdomain}.okta-emea.com/api/v1/authn'
```

It might be possible to autodetect this with the recon module by inspecting the `AuthURL` parameter in the response for https://login.microsoftonline.com/getuserrealm.srf?login=test@[customer-domain]. Another way would be to add a specific argument or prompt in interactive mode.

**Comment by TheTechromancer** [comment]
Thanks for the feature request. This feature has been added in https://github.com/blacklanternsecurity/TREVORspray/commit/cbf72e6c00f6bf357d961dc1d891db3e3447e129. Users are now prompted for the entire domain instead of only the subdomain.
