### ISSUE TITLE
trevorspray is not running

### ISSUE THREAD

**Issue by ctpentest01** [blacklanternsecurity/TREVORspray#28]
Getting the following error when trying to run the trevorspray:

└─# trevorspray --recon example.com
Traceback (most recent call last):
  File "/usr/local/bin/trevorspray", line 5, in <module>
    from trevorspray.cli import main
  File "/usr/local/lib/python3.11/dist-packages/trevorspray/cli.py", line 24, in <module>
    from lib import logger
ImportError: cannot import name 'logger' from 'lib' (/usr/lib/python3/dist-packages/lib/__init__.py)

I have installed it using the following commands:
pip3 install git+https://github.com/blacklanternsecurity/trevorproxy
pip3 install git+https://github.com/blacklanternsecurity/trevorspray

**Comment by TheTechromancer** [comment]
Thanks for the report. This is fixed in https://github.com/blacklanternsecurity/TREVORspray/commit/05b9cd9c47c1def01aac56cf469312b3bd66473e.
