### ISSUE TITLE
Proxythread Error (OWA)

### ISSUE THREAD

**Issue by barrett092** [blacklanternsecurity/TREVORspray#34]
I'm getting this error anytime I try against an OWA instance:

[ERRR] Unhandled error in OWA.create_request(): BaseSprayModule.create_request() missing 1 required positional argument: 'proxythread' (-v to debug)
[ERRR] Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/trevorspray/lib/proxy.py", line 268, in check_cred
    prepared_request = sprayer.create_request(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/trevorspray/lib/sprayers/owa.py", line 71, in create_request
    r = super().create_request(username, password)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseSprayModule.create_request() missing 1 required positional argument: 'proxythread'

**Comment by TheTechromancer** [comment]
Thanks for the report, I'll check it out.

**Comment by TheTechromancer** [comment]
A [fix](https://github.com/blacklanternsecurity/TREVORspray/commit/53c8809776abe4e4962cbe415bd1b1a19a044381) has been pushed in the latest version (`v2.2.1`).
