### ISSUE TITLE
Using TREVORSpray against ADFS portal

### ISSUE THREAD

**Issue by zeroploitable** [blacklanternsecurity/TREVORspray#4]
Hi,

Can I use TREVORSpray In the case where the o365 login page redirects to an adfs login page?

When I tried it the output was showing success for all emails! Is there any way to differentiate the response?

Thank you.

**Comment by TheTechromancer** [comment]
This should work as long as you have the correct OAUTH URL. I have added a `--recon` flag to enumerate it.
