### ISSUE TITLE
No matching distribution found for trevorproxy in Ubuntu 18.04

### ISSUE THREAD

**Issue by iknowjason** [blacklanternsecurity/TREVORspray#5]
In Ubuntu 18.04, getting the following error.  I have yet to be able to trace down the exact issue with trevorproxy dependencies that are missing in Bionic Beaver.  Is Ubuntu 18.04 supported as an OS or are you just recommending we use Ubuntu 20.04 or later?

Exact error when running install:

ERROR: Could not find a version that satisfies the requirement trevorproxy<2.0.0,>=1.0.1 (from trevorspray)
ERROR: No matching distribution found for trevorproxy<2.0.0,>=1.0.1

Thanks.  TrevorSpray is a very nice tool.
-Jason

**Comment by TheTechromancer** [comment]
What happens when you do `pip install trevorproxy`?

**Comment by iknowjason** [comment]
I get this below.  Attaching screen shot of the error.  
```
ERROR: Cannot install trevorspray==1.0.0, trevorspray==1.0.1 and trevorspray==1.0.2 because these package versions have conflicting dependencies.
```
![error](https://user-images.githubusercontent.com/4335973/149856704-41bdb4dc-beba-4d04-a6ac-02401ea0bf6e.png)

**Comment by TheTechromancer** [comment]
That error doesn't make sense to me since the versions don't actually seem to conflict. Try uninstalling trevorspray and then installing both tools directly from their github repos:
```
$ pip install --no-cache-dir git+https://github.com/blacklanternsecurity/trevorproxy
$ pip install --no-cache-dir git+https://github.com/blacklanternsecurity/trevorspray@trevorspray-v2
```

**Comment by iknowjason** [comment]
Yeah that is really odd.  I took your suggestion.  I didn't un-install trevorspray.  But both of those commands worked perfectly well to install.  Now it is working.  Odd that the initial install didn't work but installing the tools directly from their github repos does work.

**Comment by iknowjason** [comment]
Thanks for the assist.  Good to go.
