### ISSUE TITLE
Error when trying to execute trevorspray

### ISSUE THREAD

**Issue by bandrel** [blacklanternsecurity/TREVORspray#8]
Get the following error when trying to execute trevorspray
`ModuleNotFoundError: No module named 'lib.trevor'`

**Comment by TheTechromancer** [comment]
How did you install the tool? And what is the full command that you ran?

**Comment by bandrel** [comment]
Multiple methods but I was able to reproduce in a docker container

![2022-01-27_11-48-11](https://user-images.githubusercontent.com/3598052/151404835-f6bb4e75-229a-40c3-8d3b-b594898cc2b6.png)

```docker
from python:3.6

RUN apt update
RUN apt install python3-pip -y
RUN apt install git -y
RUN python3 -m pip install git+https://github.com/blacklanternsecurity/trevorproxy
RUN python3 -m pip install git+https://github.com/blacklanternsecurity/trevorspray

**Comment by TheTechromancer** [comment]
Nice find. This should be fixed now. Can you try rebuilding the container with `docker build --no-cache`?

**Comment by bandrel** [comment]
Fixed. thank you
